# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: cloud.google.com/v1
kind: ServiceLevelObjective
metadata:
  name: gke-app-availability
  labels:
    service_name: gke
    feature_name: app
    slo_name: availability
    team_name: app-team-1
    env: dev
spec:
  description: 98% of GKE HTTP requests have valid HTTP response codes
  goal: 0.98
  backend: cloud_service_monitoring
  exporters: [pubsub, cloud_monitoring]
  method: basic_sli
  serviceLevelIndicator:
    clusterIstio:
      projectId: microservices-demo-prod-a5b2
      location: europe-west1
      clusterName: demo
      serviceNamespace: default
      serviceName: adservice
    availability: {}
