# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-generator-config
data:
  backends:
  - name: cm
    class: CloudMonitoring
    projectId: ${STACKDRIVER_HOST_PROJECT_ID}

  - name: csm
    class: CloudServiceMonitoring
    projectId: ${STACKDRIVER_HOST_PROJECT_ID}

  - name: elk
    class: Elasticsearch
    url: ${ELASTICSEARCH_URL}
    index: test_data
    dateField: last_updated

  - name: prometheus
    class: Prometheus
    url: ${PROMETHEUS_PUSHGATEWAY_URL}

  exporters:
  - name: cloud-monitoring
    class: CloudMonitoringExporter
    projectId: ${STACKDRIVER_HOST_PROJECT_ID}
    # TODO: Improve this
    metrics:
      - type: custom.googleapis.com/slo/error_budget_burn_rate
        metric_kind: GAUGE
      - type: custom.googleapis.com/slo/sli_value
        metric_kind: GAUGE

  - name: prometheus
    class: PrometheusExporter
    url: prom-gateway:8080
    metrics:
      - slo/error_budget_burn_rate
      - slo/sli_value

  - name: bigquery
    class: BigqueryExporter
    projectId: ${BIGQUERY_PROJECT_ID}

  - name: pubsub
    class: PubsubExporter
    projectId: ${PUBSUB_PROJECT_ID}
    topicName: ${PUBSUB_TOPIC_NAME}

  alerting:
    backends:
      - name: cloud-monitoring
        class: CloudMonitoring
        projectId: ${STACKDRIVER_HOST_PROJECT_ID}
        notifications:
          - channel-1
          - channel-2

      - name: prometheus-alert-manager
        class: AlertManager
        url: ${ALERT_MANAGER_URL}

    alerts:
      - name: high-burn-rate
        backend: cloud-monitoring
        displayName: SLO burn rate too high
        combiner: OR
        conditions:
        - displayName: SLO burn rate
          conditionThreshold:
            aggregations:
              alignmentPeriod: 60s
              crossSeriesReducer: REDUCE_MEAN
              groupByFields:
                  - project
                  - resource.label.instance_id
                  - resource.label.zone
              perSeriesAligner: ALIGN_MAX
          comparison: COMPARISON_GT
          duration: 900s
          filter: >
            metric.type=compute.googleapis.com/instance/cpu/utilization
            resource.type=gce_instance
          thresholdValue: auto
          trigger:
            count: 1

  error_budget_policies:
    - name: error-budget-policy-ssm
      steps:
      - name: 24 hours
        window: 86400
        burn_rate_threshold: 4
        alert: true
        message_alert: Page to defend the SLO
        message_standard: Last 24 hours on track

      - name: 48 hours
        window: 172800
        burn_rate_threshold: 2
        alert: true
        message_alert: Page to defend the SLO
        message_standard: Last 48 hours on track
