name: Deploy slo-generator service (Cloud Run)

on:
  push:
    branches:
      - master
    paths:
      - app.yaml
      - config.yaml
jobs:
  deploy-cloudrun-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy service to Cloud Run
        run: ./deploy_cloudrun_service.sh
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }} 
          
