name: Deploy slo-generator SLOs (GKE)

on:
  push:
    branches:
      - master
    # paths:
    #   - slos/*
jobs:
  deploy-gke-slos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Get container credentials
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --project=${{ secrets.PROJECT_ID }} --region=${{ secrets.REGION }}

      - name: Install dependencies
        run: ./deploy_k8s_slos.sh   
